### ISSUE TITLE
Exception: yfinance failed to decrypt Yahoo data response

### ISSUE THREAD

**Issue by mLiXin** [seohyunjun/yahoo-earnings-calendar#1]
I got an exception : yfinance failed to decrypt Yahoo data response, how can i fix it ?
code : 
```import datetime
from yahoo_earnings_calendar import YahooEarningsCalendar

date_from = datetime.datetime.strptime(
    'Feb 2 2022  10:00AM', '%b %d %Y %I:%M%p')
date_to = datetime.datetime.strptime(
    'Feb 2 2022  1:00PM', '%b %d %Y %I:%M%p')
yec = YahooEarningsCalendar()
print(yec.earnings_on(date_from))
print(yec.earnings_between(date_from, date_to))```

**Comment by seohyunjun** [comment]
I think some decrypt error in yfinance,, 

test yfinance-0.2.11 recent version (23/02/16)  but same error. 

An error occurs during the decrpyt process because the key cannot be obtained.

refer to https://github.com/ranaroussi/yfinance/issues/1407

I'll comment when the error is resolved.

**Comment by seohyunjun** [comment]
yahoo finance page stuck scrapping page information. 

so use yahoo finance API  

it is different method yahoo-earningdates-calendar

refer this site please.
https://financeapi.net/
